name: Deploy to Development Server
on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploying to Development Server
    runs-on: [ self-hosted, to-do-vm ]
    environment: development
    env:
      CONTAINER_NAME: To-Do-App
      IMAGE_NAME_TAG: to-do-app:latest
      HOST_PORT: 3000
      CONTAINER_PORT: 3000

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          clean: False

      - name: Building and Assigning Tag to image
        run: |
          docker build -t $IMAGE_NAME_TAG .

      - name: Removing old Container if exists
        run: |
          docker stop $CONTAINER_NAME || true && docker rm $CONTAINER_NAME || true

      - name: Starting Docker Container
        run: |
          docker run -d -p $HOST_PORT:$CONTAINER_PORT --restart unless-stopped --name $CONTAINER_NAME  $IMAGE_NAME_TAG

      - name: View Docker status
        run: |
          docker ps

      - name: Cleaning Server
        run: |
          echo y | docker system prune -a
          